"""Grok Imagine client for Scutaris card images (HACKMIT_PLAN_v3 FIX 4).

`generate_image` is the public entry point. With no `XAI_API_KEY` (or with
`USE_MOCK_IMAGINE=1`) it returns the static placeholder under `/static/mocks/`
and never calls xAI. Generated bytes are written to
`backend/static/grok_cache/<sha256>.png` so a second identical request is a
cache hit.

Env is loaded through `backend.config.get_settings()` (which reads `.env`);
Imagine-specific keys are then read with `os.getenv` because they are not on
the `Settings` dataclass. The API key is never logged or returned.
"""

from __future__ import annotations

import base64
import hashlib
import json
import logging
import os
import shutil
import time
from pathlib import Path
from typing import Any, Mapping

import httpx

from backend.config import get_settings

logger = logging.getLogger(__name__)

XAI_IMAGES_URL = "https://api.x.ai/v1/images/generations"
XAI_IMAGE_MODEL = "grok-imagine-image-2.0"

STATIC_DIR: Path = Path(__file__).resolve().parent / "static"
MOCK_DIR: Path = STATIC_DIR / "mocks"
CACHE_DIR: Path = STATIC_DIR / "grok_cache"

MOCK_NOTE = "Grok Imagine mock mode — XAI_API_KEY unset or USE_MOCK_IMAGINE=1."

#: FIX 4 templates. Brand palette: teal #5eead4, amber #fbbf24, red #ef4444.
PROMPT_TEMPLATES: dict[str, str] = {
    "risk_card": (
        "Cinematic space-ops risk card. Conjunction {primary_name} "
        "(NORAD {primary_norad}) vs {secondary_name} (NORAD {secondary_norad}). "
        "TCA {tca_utc}. Miss {miss_km} km. Risk {risk_level}. "
        "Dark HUD poster, teal orbit arcs (#5eead4), amber (#fbbf24) or red "
        "(#ef4444) by severity, no gore, square."
    ),
    "object_card": (
        'Mission-patch emblem for "{name}" (NORAD {norad_id}), {orbit_class}. '
        "Dark badge, teal (#5eead4) linework, minimal type, no crash imagery."
    ),
    "scenario_card": (
        'Atmospheric LEO scene for query "{query}". Earth limb, sparse debris '
        "sparks, teal HUD (#5eead4), amber watch highlights (#fbbf24), dark "
        "cinematic frame."
    ),
}

#: Curl / UI shortcuts → FIX 4 template keys.
_CONTEXT_ALIASES: dict[str, str] = {
    "primary": "primary_name",
    "secondary": "secondary_name",
    "primary_norad_id": "primary_norad",
    "secondary_norad_id": "secondary_norad",
    "tca": "tca_utc",
    "object_name": "name",
    "norad": "norad_id",
}

_PLACEHOLDER = "unknown"
_warned_mock = False


class ImagineError(RuntimeError):
    """Raised when the xAI Imagine call fails and the caller should degrade."""


class _DefaultingContext(dict):
    """Renders missing template keys as `unknown` instead of raising."""

    def __missing__(self, key: str) -> str:
        return _PLACEHOLDER


def _ensure_cache_dir() -> Path:
    """Create the on-disk cache directory if it is missing."""
    CACHE_DIR.mkdir(parents=True, exist_ok=True)
    return CACHE_DIR


def _load_env() -> None:
    """Force `.env` into `os.environ` via the shared Settings loader."""
    get_settings()


def _truthy(raw: str) -> bool:
    """Return True for common affirmative env values (`1`, `true`, `yes`, `on`)."""
    return raw.strip().lower() in {"1", "true", "yes", "on"}


def imagine_is_mock() -> bool:
    """True when Imagine must not call xAI (missing key or explicit mock flag)."""
    _load_env()
    key = os.getenv("XAI_API_KEY", "").strip()
    flag = os.getenv("USE_MOCK_IMAGINE", "")
    return (not key) or _truthy(flag)


def _xai_url() -> str:
    """Image-generation URL, overridable via `XAI_API_URL`."""
    _load_env()
    return os.getenv("XAI_API_URL", "").strip() or XAI_IMAGES_URL


def _xai_model() -> str:
    """Imagine model id, overridable via `XAI_IMAGE_MODEL`."""
    _load_env()
    return os.getenv("XAI_IMAGE_MODEL", "").strip() or XAI_IMAGE_MODEL


def _warn_mock_once() -> None:
    """Log a single warning the first time mock mode serves a card."""
    global _warned_mock
    if _warned_mock:
        return
    logger.warning(MOCK_NOTE)
    _warned_mock = True


def cache_key(card_type: str, context: Mapping[str, Any]) -> str:
    """sha256 of `card_type` plus canonical JSON of `context`."""
    payload = card_type + json.dumps(context, sort_keys=True, default=str)
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()


def cache_path(digest: str) -> Path:
    """Absolute path of the cached PNG for `digest`."""
    return _ensure_cache_dir() / f"{digest}.png"


def cache_url(digest: str) -> str:
    """Public URL path for a cached PNG."""
    return f"/static/grok_cache/{digest}.png"


def mock_url(card_type: str) -> str:
    """Public URL path of the static placeholder for `card_type`."""
    return f"/static/mocks/{card_type}.png"


def _filled_context(context: Mapping[str, Any]) -> dict[str, Any]:
    """Copy `context` and apply FIX 4 aliases without overwriting real keys."""
    filled = dict(context)
    for src, dest in _CONTEXT_ALIASES.items():
        if dest not in filled and src in filled:
            filled[dest] = filled[src]
    return filled


def build_risk_card_prompt(context: dict[str, Any]) -> str:
    """Fill the FIX 4 risk-card template (conjunction HUD poster)."""
    return PROMPT_TEMPLATES["risk_card"].format_map(
        _DefaultingContext(_filled_context(context))
    )


def build_object_card_prompt(context: dict[str, Any]) -> str:
    """Fill the FIX 4 object-card template (mission-patch emblem)."""
    return PROMPT_TEMPLATES["object_card"].format_map(
        _DefaultingContext(_filled_context(context))
    )


def build_scenario_card_prompt(context: dict[str, Any]) -> str:
    """Fill the FIX 4 scenario-card template (LEO debris overview)."""
    return PROMPT_TEMPLATES["scenario_card"].format_map(
        _DefaultingContext(_filled_context(context))
    )


def build_prompt(card_type: str, context: Mapping[str, Any]) -> str:
    """Dispatch to the FIX 4 builder for `card_type`."""
    builders = {
        "risk_card": build_risk_card_prompt,
        "object_card": build_object_card_prompt,
        "scenario_card": build_scenario_card_prompt,
    }
    try:
        builder = builders[card_type]
    except KeyError as exc:
        raise ImagineError(f"Unknown card type {card_type!r}") from exc
    return builder(dict(context))


def _result(
    *,
    image_url: str,
    prompt_used: str,
    cached: bool,
    took_ms: int,
    mock: bool,
) -> dict[str, Any]:
    """Assemble the dict `generate_image` returns (matches VisualizeResponse fields)."""
    return {
        "image_url": image_url,
        "prompt_used": prompt_used,
        "cached": cached,
        "took_ms": took_ms,
        "mock": mock,
    }


def _copy_mock_into_cache(card_type: str, digest: str) -> None:
    """Seed the cache with the static placeholder so the next call is a hit."""
    source = MOCK_DIR / f"{card_type}.png"
    dest = cache_path(digest)
    if source.is_file():
        shutil.copyfile(source, dest)
        return
    dest.write_bytes(b"")


async def _download_image_bytes(client: httpx.AsyncClient, payload: dict[str, Any]) -> bytes:
    """Extract image bytes from an xAI `images.generations` JSON body."""
    data = payload.get("data") or []
    if not data:
        raise ImagineError("xAI Imagine response had no data[]")
    first = data[0] if isinstance(data[0], dict) else {}
    b64 = first.get("b64_json")
    if b64:
        return base64.b64decode(b64)
    url = first.get("url")
    if not url:
        raise ImagineError("xAI Imagine response had neither b64_json nor url")
    downloaded = await client.get(url, headers={})
    downloaded.raise_for_status()
    return downloaded.content


async def _call_xai(prompt: str) -> bytes:
    """POST the Imagine request and return raw image bytes. Never logs the key."""
    _load_env()
    api_key = os.getenv("XAI_API_KEY", "").strip()
    settings = get_settings()
    timeout = max(settings.http_timeout, 60.0)
    body = {
        "model": _xai_model(),
        "prompt": prompt,
        "n": 1,
        "aspect_ratio": "1:1",
        "response_format": "b64_json",
    }
    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json",
    }
    async with httpx.AsyncClient(timeout=timeout, follow_redirects=True) as client:
        response = await client.post(_xai_url(), json=body, headers=headers)
        if response.status_code >= 400:
            raise ImagineError(
                f"xAI Imagine HTTP {response.status_code}: {response.text[:300]}"
            )
        return await _download_image_bytes(client, response.json())


async def generate_image(card_type: str, context: dict) -> dict:
    """Build a FIX 4 prompt and return a (possibly cached or mock) image URL.

    Returns a dict with `image_url`, `prompt_used`, `cached`, `took_ms`, `mock`.
    """
    started = time.perf_counter()
    prompt = build_prompt(card_type, context)
    mock_mode = imagine_is_mock()

    if mock_mode:
        _warn_mock_once()
        return {
            "image_url": f"/static/mocks/{card_type}.png",
            "prompt_used": prompt,
            "cached": False,
            "mock": True,
            "took_ms": 0,
        }

    digest = cache_key(card_type, context)
    dest = cache_path(digest)
    cache_hit = dest.is_file() and dest.stat().st_size > 0

    if cache_hit and os.path.exists(dest):
        return {
            "image_url": cache_url(digest),
            "prompt_used": prompt,
            "cached": True,
            "mock": False,
            "took_ms": int((time.perf_counter() - started) * 1000),
        }

    try:
        image_bytes = await _call_xai(prompt)
        result = _result(
            image_url=cache_url(digest),
            prompt_used=prompt,
            cached=False,
            took_ms=int((time.perf_counter() - started) * 1000),
            mock=False,
        )
        if mock_mode:
            return result
        dest.write_bytes(image_bytes)
    except Exception as exc:  # noqa: BLE001 - caller decides how to degrade
        raise ImagineError(f"{type(exc).__name__}: {exc}") from exc

    return result
